// demos/react/src/domain/animation/views/animation-list/TitleField.tsx
import type { ReactNode } from 'react';

import { StringFieldStructuralWidget } from '@/shared/components/widget/base';

export default class AnimationListTitleFieldWidget extends StringFieldStructuralWidget {
  public render(): ReactNode {
    return (
      <a
        href={`https://otaku-ism.com/animations/${this.$$view.getFieldValue('id')}/`}
        target='_blank'
        rel='noreferrer'
      >
        {this.props.value}
      </a>
    );
  }
}

// demos/vue/src/domain/game/views/game-list/TitleField.vue
<template>
  <a :href="`https://otaku-ism.com/games/${row.id}/`" target="_blank">{{ value }}</a>
</template>

<script lang="ts">
import { Component } from 'vue-property-decorator';

import { StringFieldStructuralWidget } from '@/components/widget/base';

@Component
export default class GameListTitleField extends StringFieldStructuralWidget {
  private get row() {
    return this.$$view.getValue();
  }
}
</script>
