// demos/react/src/domain/animation/views/animation-list/EpisodesField.tsx
import { ReactNode } from 'react';

import { AnimationEntity } from '@_/modules/animation/typing';

import { RelationFieldStructuralWidget } from '@/shared/components/widget/base';

export default class AnimationListEpisodesFieldWidget extends RelationFieldStructuralWidget<
  AnimationEntity[]
> {
  public render(): ReactNode {
    return <span>{(this.props.value || []).length}</span>;
  }
}

// demos/vue/src/domain/animation/views/animation-list/EpisodesField.vue
<template>
  <span>{{ count }}</span>
</template>

<script lang="ts">
import { Component } from 'vue-property-decorator';

import type { AnimationEntity } from '@_/modules/animation/typing';

import { RelationFieldStructuralWidget } from '@/components/widget/base';

@Component
export default class AnimationListEpisodesFieldWidget extends RelationFieldStructuralWidget<
  AnimationEntity[]
> {
  private get count() {
    return (this.value || []).length;
  }
}
</script>
